const SOCKET_SERVER_URL = 'https://rsclone-node-js.herokuapp.com/';
const ROLE = 'ROLE';
const ROLE_PAINTER = 'PAINTER';
const ROLE_GUESSER = 'GUESSER';
const NAME = 'NAME';
const USERS = 'USERS';
const DRAW_THICKNESS = 'DRAW_THICKNESS';
const DRAW_COLOR = 'DRAW_COLOR';
const DELETE_USERS = 'DELETE_USERS';
const WORDS_TO_SELECT = 'WORDS_TO_SELECT';
const WORD_TO_GUESS = 'WORD_TO_GUESS';
const STOP_GAME = 'STOP_GAME';
const START_GAME = 'START_GAME';
const NEW_GAME = 'NEW_GAME';
const LOADING_GAME = 'LOADING_GAME';
const READY_TO_GAME = 'READY_TO_GAME';
const BROADCAST_LIKE = 'like';
const BROADCAST_DISLIKE = 'dislike';
const BROADCAST_MSG = 'msg';

module.exports = {
  SOCKET_SERVER_URL,
  ROLE_PAINTER,
  ROLE_GUESSER,
  USERS,
  NAME,
  ROLE,
  DRAW_COLOR,
  DRAW_THICKNESS,
  STOP_GAME,
  START_GAME,
  WORD_TO_GUESS,
  WORDS_TO_SELECT,
  DELETE_USERS,
  NEW_GAME,
  LOADING_GAME,
  READY_TO_GAME,
  BROADCAST_LIKE,
  BROADCAST_DISLIKE,
  BROADCAST_MSG,
};
